### ISSUE TITLE
Typo & NPM info

### ISSUE THREAD

**Issue by bransbury** [FredKSchott/the-node-way#6]
Great docs Fred, I think there is a typo in this section though: 
http://thenodeway.io/introduction/#return-early

In "replace long, nested if-else chains with smaller if statements that return as soon as some condition is **_method_**" - I'm assuming **_method_** should be **_met_**?

In the Community section the NPM stats "now hosting over 100,000 modules and over XYZ installs a day" can be updated with "over _**200,000**_ modules and over _**100 million**_ downloads a day"

**Comment by FredKSchott** [comment]
@bransbury Oh man, I can't believe I left "XYZ" in there. :see_no_evil: 

Thanks for letting me know, i'll get that fixed ASAP.

**Comment by FredKSchott** [comment]
Fixed! Thanks again.

**Comment by bransbury** [comment]
Haha, no problem 😀
